"""Add suscripcion to taller

Revision ID: 18b8803a3126
Revises: a36cc3a2d35e
Create Date: 2026-06-07 18:55:56.988634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b8803a3126'
down_revision: Union[str, Sequence[str], None] = 'a36cc3a2d35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taller', sa.Column('plan_suscripcion', sa.String(length=50), nullable=True))
    op.add_column('taller', sa.Column('suscripcion_expira', sa.DateTime(), nullable=True))
    op.add_column('taller', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taller', 'stripe_subscription_id')
    op.drop_column('taller', 'suscripcion_expira')
    op.drop_column('taller', 'plan_suscripcion')
    # ### end Alembic commands ###
