"""Add stripe account to taller

Revision ID: a36cc3a2d35e
Revises: b1f7c2a9d8e4
Create Date: 2026-06-07 18:23:21.863124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36cc3a2d35e'
down_revision: Union[str, Sequence[str], None] = 'b1f7c2a9d8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taller', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taller', 'stripe_account_id')
    # ### end Alembic commands ###
