"""Add cotizacion multiple

Revision ID: af91898a4109
Revises: 18b8803a3126
Create Date: 2026-06-07 20:26:19.715374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af91898a4109'
down_revision: Union[str, Sequence[str], None] = '18b8803a3126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidente_asignacion_candidato', sa.Column('cotizacion_monto', sa.Float(), nullable=True))
    op.add_column('incidente_asignacion_candidato', sa.Column('cotizacion_tiempo', sa.String(length=100), nullable=True))
    op.add_column('incidente_asignacion_candidato', sa.Column('sugerencia_ia_monto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidente_asignacion_candidato', 'sugerencia_ia_monto')
    op.drop_column('incidente_asignacion_candidato', 'cotizacion_tiempo')
    op.drop_column('incidente_asignacion_candidato', 'cotizacion_monto')
    # ### end Alembic commands ###
